name: Test Suite
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # platform: [ubuntu-latest, windows-latest]
        platform: [ubuntu-latest]
        php: [ "7.0", "7.1", "7.2", "7.3", "7.4", "8.0" ]
    name: PHP ${{ matrix.php }} Unit Test (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@verbose
      with:
        php-version: ${{ matrix.php }}
        extensions: grpc
    - name: Install Dependencies
      run: |
        for DIR in $(find * -maxdepth 0 -type d -name '[A-Z]*'); do {
          composer --no-interaction --no-ansi --no-progress update -d ${DIR};
        }; done
    - name: Run Unit Test Suite
      run: |
        set -e
        for DIR in $(find * -maxdepth 0 -type d -name '[A-Z]*'); do {
          ${DIR}/vendor/bin/phpunit -c ${DIR}/phpunit.xml.dist;
        }; done
    - if: ${{ matrix.platform != 'windows-latest' }}
      name: Run Snippet Test Suite
      run: |
        set -e
        for DIR in $(find * -mindepth 1 -type f -name 'phpunit-snippets.xml.dist' -exec dirname {} \;); do {
          ${DIR}/vendor/bin/phpunit -c ${DIR}/phpunit-snippets.xml.dist --verbose
        }; done

  style:
    runs-on: ubuntu-latest
    name: PHP Style Check
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer --no-interaction --no-ansi --no-progress update
    - name: Run PHPCS Code Style Checker
      run: dev/sh/style

  docs:
    runs-on: ubuntu-latest
    name: Generate Documentation (Dry Run)
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer --no-interaction --no-ansi --no-progress update
    - name: Run Docs Generator
      run: php -d 'memory_limit=-1' dev/google-cloud doc
